name: Run autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: select tests to run
        required: true
        type: choice
        default: all
        options:
          - all

jobs:
  run-tests:
    runs-on: windows-latest
    name: Tests

    steps:
      - name: Copy source data
        uses: actions/checkout@v4

      - name: Remove old allure report
        run: |
          if (Test-Path -Path "./allure-results") {
            Remove-Item -Recurse -Force ./allure-results
          }
          if (Test-Path -Path "./allure-report") {
            Remove-Item -Recurse -Force ./allure-report
          }

      - name: Set up Python env
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Run tests with Allure
        run: pytest -v --alluredir=allure-results
        
      - name: Install Scoop and Allure
        shell: powershell
        run: |
          iwr -useb get.scoop.sh | iex
          scoop install allure

      - name: Generate Allure report
        shell: powershell
        run: |
          $allurePath = "$env:USERPROFILE\scoop\apps\allure\current\bin\allure.bat"
          & $allurePath generate allure-results --clean -o allure-report
        if: always()

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
