name: Run autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: select tests to run
        required: true
        type: choice
        default: all
        options:
          - all
  repository_dispatch:
    types: [run-tests]  # <-- для запуска через API

env:
  OWNER: kirillqqqq
  REPO: test_demo_web_shop

jobs:
  run-tests:
    runs-on: windows-latest
    name: Run tests and push Allure report

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.email "your@email.com"
          git config --global user.name "Your Name"

      - name: Fetch and clean old Allure report from gh-pages
        run: |
          git fetch
          git checkout gh-pages || git checkout --orphan gh-pages
          if (Test-Path -Path "./allure-report") {
            Remove-Item -Recurse -Force ./allure-report
          }
          git rm -r --cached allure-report 2>$null
          git commit -m "Remove old allure report" || echo "Nothing to remove"
          git push origin gh-pages
          git checkout $env:GITHUB_REF_NAME

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Install Scoop and Allure
        shell: powershell
        run: |
          iwr -useb get.scoop.sh | iex
          scoop install allure

      - name: Run tests with Allure
        run: pytest --alluredir allure-results -n 2 --reruns 1 --reruns-delay 5

      - name: Generate Allure report
        shell: powershell
        run: |
          $allurePath = "$env:USERPROFILE\scoop\apps\allure\current\bin\allure.bat"
          & $allurePath generate allure-results --clean -o allure-report
        if: always()

      - name: Push Allure report to gh-pages
        run: |
          git checkout gh-pages
          Copy-Item -Recurse -Force allure-report/* .
          git add .
          git commit -m "Add new Allure report"
          git push origin gh-pages
        if: always()
